name: "Build .NET"
author: "Arbeidstilsynet"
description: "Restores, checks formatting, lints, builds, and tests a .NET solution/project"

inputs:
  working-directory:
    description: "The directory to run dotnet commands in"
    required: true
  dotnet-version:
    description: "The version of dotnet to use"
    default: "8.0.x"
  check-for-outdated-packages:
    description: "Whether to check for outdated packages"
    required: false
    default: "false"
  outdated-package-names:
    description: "A comma-separated list of nuget package names to be used in the outdated package check. If not provided, all packages are taken into consideration."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore tools
      run: dotnet tool restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Restore
      run: dotnet restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Outdated package check
      if: ${{ inputs.check-for-outdated-packages == 'true' }}
      run: |
          echo "🔍 Checking for outdated internal package references..."

          # Get outdated packages output
          OUTDATED_OUTPUT=$(dotnet list package --outdated)
          
          # Convert comma-separated package names to grep pattern
          PACKAGE_NAMES="${{ inputs.outdated-package-names }}"
          if [ -n "$PACKAGE_NAMES" ]; then
            # Convert comma-separated list to grep pattern (package1|package2|package3)
            GREP_PATTERN=$(echo "$PACKAGE_NAMES" | sed 's/,/|/g')
            FILTERED_OUTPUT=$(echo "$OUTDATED_OUTPUT" | grep -E "$GREP_PATTERN" || true)
          else
            # If no specific packages provided, check all
            FILTERED_OUTPUT="$OUTDATED_OUTPUT"
          fi

          # Check for any outdated packages
          if [ -n "$FILTERED_OUTPUT" ] && echo "$FILTERED_OUTPUT" | grep -q .; then
            echo "❌ Found outdated package references:"
            echo "$FILTERED_OUTPUT"
            echo ""
            echo "💡 It is required to update these packages before you can continue."
            exit 1
          else
            echo "✅ All internal package references are up to date"
          fi
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Security check
      run: dotnet list package --vulnerable
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: List packages
      run: dotnet list package
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Csharpier lint
      run: dotnet csharpier check .
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format style
      run: dotnet format style --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format analyzers
      run: dotnet format analyzers --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Test
      run: dotnet test --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      working-directory: ${{ inputs.working-directory }}
      shell: bash
