name: "Build .NET"
author: "Arbeidstilsynet"
description: "Restores, checks formatting, lints, builds, and tests a .NET solution/project. Can optionally run SonarQube Cloud analysis."

inputs:
  working-directory:
    description: "The directory to run dotnet commands in"
    required: true
  dotnet-version:
    description: "The version of dotnet to use"
    default: "10.0.x"
  enable-sonar:
    description: "Enable SonarQube analysis"
    default: "false"
  sonar-token:
    description: "SonarQube token"
    required: false
  sonar-organization:
    description: "SonarQube organization"
    required: false
  sonar-project-key:
    description: "SonarQube project key"
    required: false
  sonar-exclusions:
    description: "Comma-separated list of file patterns to exclude from SonarQube analysis (e.g., '**/Migrations/**,**/Utils/**')"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate SonarQube inputs
      if: inputs.enable-sonar == 'true'
      run: |
        if [ -z "${{ inputs.sonar-token }}" ]; then
          echo "::error::sonar-token is required when enable-sonar is true"
          exit 1
        fi
        if [ -z "${{ inputs.sonar-organization }}" ]; then
          echo "::error::sonar-organization is required when enable-sonar is true"
          exit 1
        fi
        if [ -z "${{ inputs.sonar-project-key }}" ]; then
          echo "::error::sonar-project-key is required when enable-sonar is true"
          exit 1
        fi
      shell: bash

    - name: Set up JDK 17
      if: inputs.enable-sonar == 'true'
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
      with:
        java-version: 17
        distribution: "zulu"

    - name: Setup .NET
      uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache SonarQube packages
      if: inputs.enable-sonar == 'true'
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube scanner
      if: inputs.enable-sonar == 'true'
      id: cache-sonar-scanner
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ${{ runner.temp }}/scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarQube scanner
      if: inputs.enable-sonar == 'true' && steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ runner.temp }}/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}/scanner
      shell: bash

    - name: Restore tools
      run: dotnet tool restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Restore
      run: dotnet restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Security check
      run: dotnet list package --vulnerable
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: List packages
      run: dotnet list package
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Csharpier lint
      run: dotnet csharpier check .
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format style
      run: dotnet format style --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format analyzers
      run: dotnet format analyzers --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Begin SonarQube analysis
      if: inputs.enable-sonar == 'true'
      run: |
        SONAR_ARGS="/o:${{ inputs.sonar-organization }}"
        SONAR_ARGS="$SONAR_ARGS /k:${{ inputs.sonar-project-key }}"
        SONAR_ARGS="$SONAR_ARGS /d:sonar.token=${{ inputs.sonar-token }}"
        SONAR_ARGS="$SONAR_ARGS /d:sonar.cs.vscoveragexml.reportsPaths=**/coverage.xml"
        if [ -n "${{ inputs.sonar-exclusions }}" ]; then
          SONAR_ARGS="$SONAR_ARGS /d:sonar.exclusions=${{ inputs.sonar-exclusions }}"
        fi
        ${{ runner.temp }}/scanner/dotnet-sonarscanner begin $SONAR_ARGS
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Test
      run: dotnet test -- --coverage --coverage-output-format xml --coverage-output coverage.xml
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: End SonarQube analysis
      if: inputs.enable-sonar == 'true'
      run: |
        ${{ runner.temp }}/scanner/dotnet-sonarscanner end /d:sonar.token="${{ inputs.sonar-token }}"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
