name: "Build .NET"
author: "Arbeidstilsynet"
description: "Restores, checks formatting, lints, builds, and tests a .NET solution/project"

inputs:
  working-directory:
    description: "The directory to run dotnet commands in"
    required: true
  dotnet-version:
    description: "The version of dotnet to use"
    default: "10.0.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore tools
      run: dotnet tool restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Restore
      run: dotnet restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Security check
      run: dotnet list package --vulnerable
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: List packages
      run: dotnet list package
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Csharpier lint
      run: dotnet csharpier check .
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format style
      run: dotnet format style --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Dotnet format analyzers
      run: dotnet format analyzers --verify-no-changes
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Test
      run: dotnet test -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml
      working-directory: ${{ inputs.working-directory }}
      shell: bash
