name: Tag Action

on:
  push:
    branches:
      - main
      - feat/add-action # temp 2
    paths:
      - "action.yml"
      - "VERSION"
      - ".github/workflows/main.yml"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read VERSION file
        id: version
        run: |
          version=$(cat VERSION | tr -d ' \r\n')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create or update tag from VERSION
        run: |
          git tag -f ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }} --force
